### ISSUE TITLE
mnemonic in document does not match instruction

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#11]
at following instructions the mnemonic in document does not match instruction format   
where is segment register?

LD [.M] r, ofs(b)      
LDO r, operand    
LDPA r, a(b)    
LDR r, ofs(b)    
PRB [.<opt>] r, operand 
STw [.M] operand, r
STC operand r

**Comment by HFF-Git** [comment]
Hallo Wolfgang,

Die Instruktionen haben ein „seg“ field. 
> LD [.M] r, ofs(b).  
> 
> LDPA r, a(b)
> 
> LDR r, ofs(b)
> 
> PRB [.] r, operand
> 
> STw [.M] operand, r
> 
> STC operand r
> 

Im Document:

-> the „seg“ field ( Bits 12, 13 ) selects the segment register. A value of zero selects implicit among SR4 to SR7, a value of 1 to 3 selects SR1 to SR3.

> LDO r, operand
> 

-> the is no segment in the LDO instruction.


Viele Grüsse, Helmut

**Comment by wesch** [comment]
Ja, aber wo ist das seg-Feld im mnemonic benannt?Am 03.06.2024 um 18:21 schrieb Helmut Fieres ***@***.***>:﻿
Hallo Wolfgang,



Die Instruktionen haben ein „seg“ field. 

> LD [.M] r, ofs(b).  

> 

> LDPA r, a(b)

> 

> LDR r, ofs(b)

> 

> PRB [.] r, operand

> 

> STw [.M] operand, r

> 

> STC operand r

> 



Im Document:



-> the „seg“ field ( Bits 12, 13 ) selects the segment register. A value of zero selects implicit among SR4 to SR7, a value of 1 to 3 selects SR1 to SR3.



> LDO r, operand

> 



-> the is no segment in the LDO instruction.





Viele Grüsse, Helmut

**Comment by HFF-Git** [comment]
Das gehört in die Klammer, wenn SR1 bis SR3 gewünscht wird…. Ich addiere es …

**Comment by HFF-Git** [comment]
Added clarification to document.
