### ISSUE TITLE
Instruction Issues

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#12]
dis 0xC1E800E4 should give LDB.X r7, r14(s2, r4) but gives LDB.X r7, r2(s14, r4)
     by the way: the .X is not needed because the format is anyway different

dis 0xC5C200E4 should give ST 0xe(r4), r7 but gives ST 0xe(r4), r4
     would be nice if offset is decimal...

dis 0xE9C000E4 should give PRB.I r7, (r4)  but gives PRB.R r7, (r4), 0

**Comment by HFF-Git** [comment]
See comments below:

> Am 11.06.2024 um 18:31 schrieb WolfgangE ***@***.***>:
> 
> 
> dis 0xC1E800E4 should give LDB.X r7, r14(s2, r4) but gives LDB.X r7, r2(s14, r4)
> by the way: the .X is not needed because the format is anyway different
> 

Fixed. Two fields were mixed up. Removed the „.X“ output.

> dis 0xC5C200E4 should give ST 0xe(r4), r7 but gives ST 0xe(r4), r4
> would be nice if offset is decimal...
> 

Fixed. The output is decimal now. And also prints correctly:  ST 7 (R4), R7

> dis 0xE9C000E4 should give PRB.I r7, (r4) but gives PRB.R r7, (r4), 0
> 

Fixed. The output should be:  PRB.RI r7, (r4), 0 (0xe9c000e4) and is now.

**Comment by HFF-Git** [comment]
Resolved
