### ISSUE TITLE
Unclear description Operand Encoding

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#14]
In section Operand Encoding for computational instructions

....... Operand mode 2 is the register indexed address mode, which will use a base register "b" and add an offset in "a" to it, forming the final byte address offset. The upper two bits select one of the segment registers SR4 .. SR7.

It is unlcear which two bits of what are used .

**Comment by HFF-Git** [comment]
“A” is added to “B” forms the byte address offset. The upper two bits of this offset select among the segment register SR4 to SR7. Zero maps to SR4, one to SR5 and so on.

**Comment by HFF-Git** [comment]
The same logic applies to mode 3. The upper two bits of the address formed by adding the offset encoded to”B” result in the final offset and the upper two bits select the segment register…
