### ISSUE TITLE
Compiler Error Visual Studio Windows

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#2]
In VCPU32-Driver.hpp line 622:
   static const uint MAX_FILE_NAME_SIZE = 256 

creates  compiler error C3646 unknown override specifier

**Comment by HFF-Git** [comment]
Probier bitte mal das "static" wegzulassen...

**Comment by wesch** [comment]
Hilft leider nichts. Habe jetzt einfach char    fileName[ 256 ]; gesetzt. 
Es gibt noch einen anderen Fehler (war schon gestern) : 
VCPU32-Mem.cpop Zeile 661:  funktion random() existiert nicht geändert auf 

 if ( reqTargetSet >= cDesc.blockSets ) reqTargetSet = rand( ) % cDesc.blockSets;
