### ISSUE TITLE
Offset in branch instructions

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#4]
Sollte bei Offset in branches nicht auch das signbit auf Bit 31 dargestellt werden?

**Comment by HFF-Git** [comment]
Immer das rightmost bit im Offset Feld. Richtig.Ich hätte noch eine Idee zum diskutieren. Was wäre wenn wir tatsächlich 16 Index Register erlauben. Das opMode Feld unterteilt sich ja eh schon:Bit 13,14 ist der eigentliche opMode.0 - immediate1 - Register2 - register indexed3 - indexedBit 15,16,17 index reg num - 8.Die vier Gruppen bleiben so. Auch die Syntax natürlich…Dann folgt je nach Mode die Gruppen Details. Nur Gruppe 3 würde sich ändern. Wir schieben die seg Bits auf 15,16.Dann folgt der Offset Teil.Und in dem B Feld ( 28..31) das Index Register. Voila.Ist konsistent mit Register Index Mode. Dort steht b auch am Ende.Der Preis: Offset ist ein 11 Bit Feld. Erlaubt + 255 / -256 Word addressing. ABER: wir müssen uns bei der Register Wahl für Indizierung keine Gedanken machen, die HW wird noch mal einfacher und „normale“ Routinen haben eher kleine lokale Bereiche. Größere lokale Offset gehen ja immer noch mit Register indexed.Ich wäre sehr dafür Viele Grüsse, HelmutSent from my iPadOn 28. Mar 2024, at 15:43, WolfgangE ***@***.***> wrote:﻿
Sollte bei Offset in branches nicht auch das signbit auf Bit 31 dargestellt werden?

**Comment by HFF-Git** [comment]
Alternative nehmen wir es überall raus und verweisen auf unsere Interpretation dieses Feldes.Sent from my iPadOn 28. Mar 2024, at 15:43, WolfgangE ***@***.***> wrote:﻿
Sollte bei Offset in branches nicht auch das signbit auf Bit 31 dargestellt werden?

**Comment by wesch** [comment]
Die Idee mit den 16 indexregistern hat was. Ich bin dafür. Es vereinfacht die Sache auch von der Denke her erheblich. Änderst du die Doku entsprechend?

**Comment by HFF-Git** [comment]
Vorauseilend habe ich einen branch aufgemacht und bin schon dran :-)
