### ISSUE TITLE
Disassembler issues in 16-index regsiter branch

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#6]
soll ADD R15,2				dis 0x43C00004		ist ADD r15,0x2			please show in dec	
soll ADD R15,R4				dis 0x43C20004		ist ADD r15,0,r4			error

all other modes are ok for ADD

Header of Simulator should show the version and branch

VCPU-32 Simulator, Version: B.00.02

**Comment by HFF-Git** [comment]
Zu 0: Done. It is now decimal.

Zu 1: This is a OpMode 1, SubOpMode 0 Instruction. To show that mode, I have added to the dissembler the „0,“ part to indicate that one of the parameter ( the A value ) is a zero value.
