### ISSUE TITLE
New instructions error in doc

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#8]
1. Instruction BV, Mnemonic should be BV regR, regA, regB
2.why is condition in CBR,CBRU different from CMP,CMPU? should be the same 0=EQ,1=LT,2=NE,3=LE

**Comment by HFF-Git** [comment]
Corrected the issue in assembler syntax for BV
Aligned condition code in CMPx and CBRx instructions

**Comment by HFF-Git** [comment]
Closed
