### ISSUE TITLE
unclear operand encoding

### ISSUE THREAD

**Issue by wesch** [HFF-Git/VCPU-32#9]
Decodoing ADD Instruction leads to
dis 0x41C84064 -->ADDB r7, (s0,r4) (0x41c84064)
dis 0x41C94064 -->ADDH r7, (s2,r4) (0x41c94064) -- Why S2? only change was from byte to halfword
dis 0x41CA4064 -->ADD r7, (s0,r4) (0x41ca4064)
dis 0x41CB4064-->ADD**dw** r7, (s2,r4) (0x41cb4064) --> ok not implemented yet but again s2

**Comment by HFF-Git** [comment]
Hallo Wolfgang, 

Ich habe es korrigiert. Wir reden hier von Mode 2, also Register Indexed.  


VCPU-32 Simulator, Version: B.00.05
Git Branch: Main Branch
(0) ->dis 0x41C84064
ADDB r7, r6(r4) (0x41c84064)
(1) ->dis 0x41C94064
ADDH r7, r6(r4) (0x41c94064)
(2) ->dis 0x41CA4064
ADD r7, r6(r4) (0x41ca4064)
(3) ->dis 0x41CB4064
ADD**dw** r7, r6(r4) (0x41cb4064)
(4) ->


Viele Grüsse, Helmut

**Comment by HFF-Git** [comment]
Corrected.
